export const restArr = [
  {
    id: 1,
    title: 'Пицца плюс',
    time: '50',
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    img: 'image1.jpg',
  },
  {
    id: 2,
    title: 'Тануки',
    time: '50',
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    img: 'image2.jpg',
  },
  {
    id: 3,
    title: 'FoodBand',
    time: '50',
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    img: 'image3.jpg',
  },
  {
    id: 4,
    title: 'Жадина-пицца',
    time: '50',
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    img: 'image4.jpg',
  },
  {
    id: 5,
    title: 'Точка еды',
    time: '50',
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    img: 'image5.jpg',
  },
  {
    id: 6,
    title: 'PizzaBurger',
    time: '50',
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    img: 'image6.jpg',
  },
];
